name: Environment Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      API_URL: ${{ vars.API_URL }}
      CONFIG_MODE: ${{ vars.CONFIG_MODE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "API URL: $API_URL"
          echo "Config Mode: $CONFIG_MODE"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          echo "Deploying with API key: ${{ secrets.MY_API_KEY }}"
