name: file tree

on:
  workflow_dispatch

jobs:

  file-tree:

    runs-on: self-hosted

    steps:
    - name: Install tree
      run: |
        choco install tree -y
    - name: Reboot system
      run: |
        shutdown /r /t 0
    - name: Execute tree
      run: |
        tree > filetreelist.txt
