name: Verify file
on: [push]

jobs:
  verify:
    name: ${{ vars.JOB_NAME }}
    if: ${{ vars.EXEC_WF }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          [[ -f ${{ vars.FILE_TO_CHECK }} ]] || \\
          ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" && exit 1 )
